### PR TITLE
core: cleanups part 2 + use clang-format for tests

### PR DESCRIPTION
**Pull request by mslusarz**
This change is [Reviewable](https://reviewable.io/reviews/marcinslusarz/pmemfile/25)

### CODE REVIEW

**Comment by GBuella** [comment]
Reviewed 1 of 31 files at r1.
Review status: 1 of 31 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 216 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken0wXvFvH5k__KgNxY:-Ken0wXw5uw1GZuE9PtL:brrlse0) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/CMakeLists.txt#L216)):*
> ```CMake
> 				${CMAKE_CURRENT_SOURCE_DIR}/*.cpp
> 				${CMAKE_CURRENT_SOURCE_DIR}/*.hpp
>                         )
> ```

Well, since this commit is about style anyways:
Indentation:
spaces here, tabs around it
This mix makes it look weird on reviewable.io, I guess cuz it uses 4 space wide tabs, and your editor probably uses 8 space wide tabs

Probably it does not need to be part this PR, but we really should start using either tabs or spaces everywhere in cmake files

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25)*

**Comment by marcinslusarz** [comment]
*[CMakeLists.txt, line 216 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken0wXvFvH5k__KgNxY:-Ken48D_FfYhpmOqy--v:b-tbkknm) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/CMakeLists.txt#L216)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

Well, since this commit is about style anyways:
Indentation:
spaces here, tabs around it
This mix makes it look weird on reviewable.io, I guess cuz it uses 4 space wide tabs, and your editor probably uses 8 space wide tabs

Probably it does not need to be part this PR, but we really should start using either tabs or spaces everywhere in cmake files

</blockquote></details>

I completely agree. I'll make a PR with such change after this PR is merged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25)*

**Comment by GBuella** [comment]
Reviewed 16 of 31 files at r1.
Review status: 17 of 31 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 80 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken2Hc428DyfEUSAV9b:-Ken2Hc428DyfEUSAV9c:b-neev2j) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/src/libpmemfile-core/data.c#L80)):*
> ```C
> 	if (!c)
> 		return;
> 	struct pmemfile_block_array *block_array =
> ```

Yeah, this sounds much nicer then what we had before

---

*[src/libpmemfile-core/data.c, line 684 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken2bGscKcIQwjljJVb:-Ken2bGscKcIQwjljJVc:biznqod) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/src/libpmemfile-core/data.c#L684)):*
> ```C
> 
> 	struct pmemfile_vinode *vinode = file->vinode;
> 	struct pmemfile_inode *inode = vinode->inode;
> ```

Well, we could use one less local variable now.
A few lines below, one can just do this:

TX_SET_DIRECT(vinode->inode, mtime, tm);

But this would be just a nicety, not required for LGTM

---

*[src/libpmemfile-core/dir.c, line 309 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken3IibQ9GBxn0erIwb:-Ken3IibQ9GBxn0erIwc:b-ae0efv) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/src/libpmemfile-core/dir.c#L309)):*
> PMEMFILE_S_IFDIR |
> 			mode
Please don't split this expression, it does not seem necessary.
We can just have "PMEMFILE_S_IFIR | mode" on the next line.

---

*[src/libpmemfile-core/file.c, line 1172 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken3v77rRRKXIKU_CO1:-Ken3v77rRRKXIKU_CO2:bswljos) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/src/libpmemfile-core/file.c#L1172)):*
> ```C
> 				PMEMFILE_ACCESSPERMS, &t, vparent, NULL,
> 				info.remaining, namelen);
> 		struct pmemfile_inode *inode = vinode->inode;
> ```

Probably I would remove this local variable as well, it seems to be used in only two places.
I would write in those two places vinode->inode po prostu

Just a nicety, not required.

---

*[src/libpmemfile-core/file.c, line 1282 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken46TXYk19CfiW5s6J:-Ken46TXYk19CfiW5s6K:b-rqxvo7) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/src/libpmemfile-core/file.c#L1282)):*
> ```C
> 	os_rwlock_rdlock(&vinode->rwlock);
> 
> 	const struct pmemfile_inode *inode = vinode->inode;
> ```

ditto.

---

*[tests/core/pmemfile_test.cpp, line 242 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken5Hwe5A7SKSW1UuNI:-Ken5Hwe5A7SKSW1UuNJ:b-h9twtc) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/tests/core/pmemfile_test.cpp#L242)):*
> ```cpp
> 	bool tmp;
> 
> 	for (auto c = expected.cbegin(); c != expected.cend(); ++c) {
> ```

perhaps:
for(auto c : expected)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25)*

**Comment by GBuella** [comment]
Reviewed 6 of 31 files at r1.
Review status: 23 of 31 files reviewed at latest revision, 8 unresolved discussions.

---

*[tests/core/mt/mt.cpp, line 88 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken98E2WbMA7SJuZmQ3:-Ken98E321ZXGWOkqkNM:b-wx7skx) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/tests/core/mt/mt.cpp#L88)):*
> ```cpp
> 	long ncpus = sysconf(_SC_NPROCESSORS_ONLN);
> 	int i = 0;
> 	pthread_t *threads =
> ```

Or how about something like:

std::vector<pthread_t> threads(ncpus * 2);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25)*

**Comment by marcinslusarz** [comment]
Review status: 23 of 31 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/libpmemfile-core/data.c, line 684 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken2bGscKcIQwjljJVb:-Ken8eFlZ2LXFYwSd_he:b-cet1kj) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/src/libpmemfile-core/data.c#L684)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

Well, we could use one less local variable now.
A few lines below, one can just do this:

TX_SET_DIRECT(vinode->inode, mtime, tm);

But this would be just a nicety, not required for LGTM
</blockquote></details>

There are 3 uses of inode variable below, so not sure...

---

*[src/libpmemfile-core/dir.c, line 309 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken3IibQ9GBxn0erIwb:-Ken8pOyNtzFj3PGLNtY:b32wtd) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/src/libpmemfile-core/dir.c#L309)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

> PMEMFILE_S_IFDIR |
> 			mode
Please don't split this expression, it does not seem necessary.
We can just have "PMEMFILE_S_IFIR | mode" on the next line.
</blockquote></details>

ok

---

*[src/libpmemfile-core/file.c, line 1282 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken46TXYk19CfiW5s6J:-Ken9Kkl2NtbXWPt3gTI:bi8o6mb) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/src/libpmemfile-core/file.c#L1282)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Heh, in this case I could cache the whole expression (vinode->inode->file_data.data)

---

*[tests/core/pmemfile_test.cpp, line 242 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken5Hwe5A7SKSW1UuNI:-Ken9_jbYEI7EQJrS50-:bb7oryy) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/tests/core/pmemfile_test.cpp#L242)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

perhaps:
for(auto c : expected)
</blockquote></details>

sure

---

*[tests/core/mt/mt.cpp, line 88 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken98E2WbMA7SJuZmQ3:-Ken9ifqA5_daOUKGAhm:bdrt87c) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/tests/core/mt/mt.cpp#L88)):*
<details><summary><i>Previously, GBuella (Gábor Buella) wrote…</i></summary><blockquote>

Or how about something like:

std::vector<pthread_t> threads(ncpus * 2);
</blockquote></details>

It's not related to any of the changes in this PR, so I'll leave it for later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25)*

**Comment by GBuella** [comment]
Reviewed 8 of 31 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25)*

**Comment by GBuella** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[CMakeLists.txt, line 216 at r1](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25#-Ken0wXvFvH5k__KgNxY:-KenBnG6m7VE2mTl5olr:b32w0x) ([raw file](https://github.com/marcinslusarz/pmemfile/blob/2d2e2647553fd6cb43885686217cd37dcb9af766/CMakeLists.txt#L216)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I completely agree. I'll make a PR with such change after this PR is merged.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/marcinslusarz/pmemfile/25)*

**Comment by marcinslusarz** [comment]
Merged by hand.

**Pull request closed without merging**
